# -*- coding: utf-8 -*-
"""lp_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHQc2ROx6N3PSq1WRUNWLbPuaOEgR0eL
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="WTk7xwpcPiexGkHU2cH4")
project = rf.workspace("s-workspace-hw4ln").project("my-first-project-mm79r")
version = project.version(3)
dataset = version.download("yolov8")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="WTk7xwpcPiexGkHU2cH4")
project = rf.workspace("s-workspace-hw4ln").project("my-first-project-mm79r")
version = project.version(4)
dataset = version.download("yolov8")

!pip install ultralytics

import cv2
from google.colab.patches import cv2_imshow
from ultralytics import YOLO

# YOLOv8 모델 불러오기 (nano 모델 사용)
model = YOLO('yolov8n.pt')

!yolo task=detect mode=train model=yolov8n.pt data=My-First-Project-4/data.yaml epochs=50 imgsz=1024 batch=16

#추가 학습
from ultralytics import YOLO

model = YOLO('/content/runs/detect/train-5/weights/best.pt')

results = model.train(
    data='My-First-Project-4/data.yaml',
    epochs=50,
    imgsz=1024,
    batch=16,
    patience=10,
    lr0=0.001
)

from ultralytics import YOLO

# 파인튜닝된 모델 파일 불러오기
model = YOLO('/content/runs/detect/train-6/weights/best.pt')

results = model.predict(source='Input.mp4', save=True)