# -*- coding: utf-8 -*-
"""YOLO_blur_and_emoji

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5APoVuOeW4Kg3h72Jry7e6BkfC0jl7Z
"""

from google.colab import drive
drive.mount('/content/drive')

# 1. 라이브러리 설치
!pip install ultralytics ensemble-boxes

# 2. 모델 가중치 다운로드
# gdown을 사용해 구글 드라이브 링크의 파일을 다운
import gdown
url = 'https://drive.google.com/uc?id=1ZD_CEsbo3p3_dd8eAtRfRxHDV44M0djK'
output = '/content/drive/MyDrive/YOLO/yolov8n-face.pt'
gdown.download(url, output, quiet=False)

import cv2
import numpy as np
from ultralytics import YOLO
from google.colab.patches import cv2_imshow

# 모델 로드
model = YOLO('/content/drive/MyDrive/YOLO/yolov8n-face.pt')

!pip install fastapi uvicorn pyngrok nest_asyncio python-multipart opencv-python ultralytics face_recognition -q

import os
import shutil
import json
import nest_asyncio
import cv2
import numpy as np
import torch
import face_recognition
import gc
from fastapi import FastAPI, BackgroundTasks, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, StreamingResponse
import uvicorn
from pyngrok import ngrok
from ultralytics import YOLO

# 코랩 환경 비동기 충돌 방지 패치
nest_asyncio.apply()

app = FastAPI(title="Video Blur Service API")

# CORS 허용 규칙 초기화
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# 1. AI 모델 세팅 및 하이퍼파라미터 조율
print("[서버] 고정밀 모델 레이어를 로드하는 중...")
try:
    lp_model = YOLO("/content/drive/MyDrive/YOLO/best_checkpoint_35ep.pt")
    face_model = YOLO("/content/drive/MyDrive/YOLO/yolov8n-face.pt")
    print("[서버] 고정밀 모델 체인 로드 완료")
except Exception as e:
    print(f"[서버 에러] 모델 로드 실패: {str(e)}")

# 하이퍼파라미터 튜닝
face_imgsz = 640
lp_imgsz = 1024  # 원거리 자동차 번호판 정밀 캡처용 고해상도 고정
face_conf = 0.25
lp_conf = 0.20
radius_scale_face = 1.35
radius_scale_lp = 1.35
min_face_radius = 35
min_lp_radius = 22
blur_kernel = 99

DRIVE_EMOJI_DIR = "/content/drive/MyDrive/YOLO/emoji"
os.makedirs(DRIVE_EMOJI_DIR, exist_ok=True)


# 2. 비식별화 그래픽스 엔진 헬퍼 함수들
def blur_circle_roi(frame, cx, cy, radius):
    h, w = frame.shape[:2]
    x1, y1 = max(0, int(cx - radius)), max(0, int(cy - radius))
    x2, y2 = min(w, int(cx + radius)), min(h, int(cy + radius))
    if x2 <= x1 or y2 <= y1: return
    roi = frame[y1:y2, x1:x2]
    mask = np.zeros((roi.shape[0], roi.shape[1]), dtype=np.uint8)
    cv2.circle(mask, (int(cx - x1), int(cy - y1)), int(radius), 255, -1)
    blurred = cv2.GaussianBlur(roi, (blur_kernel, blur_kernel), 0)
    roi[mask == 255] = blurred[mask == 255]

def overlay_emoji(frame, cx, cy, radius, emoji_img):
    if emoji_img is None:
        blur_circle_roi(frame, cx, cy, radius)
        return
    h, w = frame.shape[:2]
    size = int(radius * 2.5)
    x1, y1 = max(0, int(cx - size // 2)), max(0, int(cy - size // 2))
    x2, y2 = min(w, int(cx + size // 2)), min(h, int(cy + size // 2))
    roi_w, roi_h = x2 - x1, y2 - y1
    if roi_w <= 0 or roi_h <= 0: return

    emoji_resized = cv2.resize(emoji_img, (roi_w, roi_h), interpolation=cv2.INTER_AREA)
    if emoji_resized.shape[2] == 4:
        alpha_mask = emoji_resized[:, :, 3] / 255.0
        for c in range(3):
            frame[y1:y2, x1:x2, c] = (emoji_resized[:, :, c] * alpha_mask + frame[y1:y2, x1:x2, c] * (1.0 - alpha_mask)).astype(np.uint8)
    else:
        frame[y1:y2, x1:x2] = emoji_resized[:, :, :3]

def blur_rect_roi(frame, cx, cy, radius):
    h, w = frame.shape[:2]
    x1, y1 = max(0, int(cx - radius * 1.2)), max(0, int(cy - radius * 0.45))
    x2, y2 = min(w, int(cx + radius * 1.2)), min(h, int(cy + radius * 0.45))
    if x2 <= x1 or y2 <= y1: return
    roi = frame[y1:y2, x1:x2]
    if roi.size > 0:
        frame[y1:y2, x1:x2] = cv2.GaussianBlur(roi, (blur_kernel, blur_kernel), 0)

def augment_and_encode_image(image_bytes):
    nparr = np.frombuffer(image_bytes, np.uint8)
    image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    if image is None: return []
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    encodings = face_recognition.face_encodings(rgb_image, model="cnn")
    if len(encodings) == 0:
        encodings = face_recognition.face_encodings(rgb_image, model="hog")
    return encodings


# 3. 데이터 동기화 및 물리 파일 DB 파트
DRIVE_OUTPUT_DIR = "/content/drive/MyDrive/video_blur_project/outputs"
LOCAL_INPUT_DIR = "/content/blur_project/inputs"
LOCAL_OUTPUT_DIR = "/content/blur_project/outputs"
DB_DIR = "/content/blur_project/db"
os.makedirs(DRIVE_OUTPUT_DIR, exist_ok=True)
os.makedirs(LOCAL_INPUT_DIR, exist_ok=True)
os.makedirs(LOCAL_OUTPUT_DIR, exist_ok=True)
os.makedirs(DB_DIR, exist_ok=True)

def write_status_file(video_id: int, status: str, error_msg: str = None):
    with open(os.path.join(DB_DIR, f"status_{video_id}.json"), "w") as f:
        json.dump({"status": status, "result_url": f"/api/blur/download/{video_id}" if status == "COMPLETED" else None, "error": error_msg}, f)

def read_status_file(video_id: int):
    path = os.path.join(DB_DIR, f"status_{video_id}.json")
    return json.load(open(path, "r")) if os.path.exists(path) else {"status": "PROCESSING", "result_url": None}

# 고성능 YOLO ByteTrack 기반 실시간 가공 코어 태스크
def blur_video_processing_task(video_id: int, input_path: str, local_output_path: str, drive_final_path: str, registered_people: list):
    cap = cv2.VideoCapture(input_path)
    if not cap.isOpened():
        write_status_file(video_id, "FAILED", "영상 파일을 열 수 없습니다.")
        return

    width, height = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS)
    if width > 1280 or height > 720: width, height = 1280, 720

    local_raw_path = local_output_path.replace(".mp4", "_raw.mp4")
    out = cv2.VideoWriter(local_raw_path, cv2.VideoWriter_fourcc(*"mp4v"), fps, (width, height))

    identity_memory = {}
    device = 0 if torch.cuda.is_available() else "cpu"

    print(f"\n[AI 가동] Video ID {video_id} 연산 루프 주행 가동...")

    try:
        while cap.isOpened():
            ret, frame = cap.read()
            if not ret: break
            frame = cv2.resize(frame, (width, height))

            # 1. YOLO ByteTrack 얼굴 탐지 및 동적 스캔
            face_res = face_model.track(frame, conf=face_conf, imgsz=face_imgsz, device=device, persist=True, verbose=False)
            if face_res and len(face_res) > 0 and face_res[0].boxes is not None and face_res[0].boxes.id is not None:
                try:
                    xywh_list = face_res[0].boxes.xywh.cpu().numpy()
                    track_ids = face_res[0].boxes.id.int().cpu().numpy()

                    for xywh, t_id in zip(xywh_list, track_ids):
                        cx, cy, bw, bh = xywh
                        radius = int(max(bw, bh) / 2 * radius_scale_face)
                        radius = max(radius, min_face_radius)

                        if t_id in identity_memory:
                            action = identity_memory[t_id]["action"]
                            emoji_img = identity_memory[t_id]["emoji_img"]
                        else:
                            margin = int(radius * 0.40)
                            x1_f, y1_f = max(0, int(cx - radius - margin)), max(0, int(cy - radius - margin))
                            x2_f, y2_f = min(width, int(cx + radius + margin)), min(height, int(cy + radius + margin))
                            face_crop = frame[y1_f:y2_f, x1_f:x2_f]

                            action, emoji_img = "blur", None

                            if face_crop.size > 0 and len(registered_people) > 0:
                                face_crop_resized = cv2.resize(face_crop, (160, 160), interpolation=cv2.INTER_CUBIC)
                                rgb_face = cv2.cvtColor(face_crop_resized, cv2.COLOR_BGR2RGB)
                                encodings = face_recognition.face_encodings(rgb_face, model="hog")

                                if len(encodings) == 0:
                                    encodings = face_recognition.face_encodings(rgb_face, model="cnn")

                                if len(encodings) > 0:
                                    face_encoding = encodings[0]
                                    distances = [np.min(face_recognition.face_distance(p["encodings"], face_encoding)) for p in registered_people]
                                    best_idx = np.argmin(distances)

                                    if distances[best_idx] <= 0.48:
                                        action = registered_people[best_idx]["action"]
                                        emoji_img = registered_people[best_idx]["emoji_img"]
                                        print(f"트래커 ID {t_id} -> 액션: {action}")

                            identity_memory[t_id] = {"action": action, "emoji_img": emoji_img}

                        if action == "no_blur": continue
                        elif action == "emoji": overlay_emoji(frame, cx, cy, radius, emoji_img)
                        else: blur_circle_roi(frame, cx, cy, radius)
                except Exception as tracker_err:
                    pass

            # 2. 원거리 자동차 번호판 스캔 루프
            lp_res = lp_model.predict(frame, conf=lp_conf, imgsz=lp_imgsz, device=device, verbose=False)
            if lp_res and len(lp_res) > 0 and lp_res[0].boxes is not None:
                try:
                    lp_xywh = lp_res[0].boxes.xywh.cpu().numpy()
                    for cx_lp, cy_lp, bw_lp, bh_lp in lp_xywh:
                        if bw_lp <= 0 or bh_lp <= 0 or (bw_lp / bh_lp) < 1.8: continue
                        radius_lp = int(bw_lp / 2 * radius_scale_lp)
                        blur_rect_roi(frame, cx_lp, cy_lp, max(radius_lp, min_lp_radius))
                except Exception as lp_err:
                    pass

            out.write(frame)

        cap.release()
        out.release()

        # FFMPEG 웹표준 인코딩 트랜스포밍 단계
        print(f"[서버] 가공 완료. 브라우저 규격 H.264 트랜스포밍 개시...")
        ffmpeg_cmd = f"ffmpeg -y -i {local_raw_path} -vcodec libx264 -pix_fmt yuv420p -profile:v high -level:v 4.0 -an {local_output_path}"
        os.system(ffmpeg_cmd)

        shutil.copy(local_output_path, drive_final_path)
        if os.path.exists(local_raw_path): os.remove(local_raw_path)

        write_status_file(video_id, "COMPLETED")
        print(f"[성공] 작업 ID {video_id} 최종 완전체 비디오 출력 성공 \n")

    except Exception as e:
        if 'cap' in locals(): cap.release()
        if 'out' in locals(): out.release()
        print(f"[에러 발생] 원인: {str(e)}")
        write_status_file(video_id, "FAILED", str(e))


# 4. FastAPI 엔드포인트 수신 제어부
video_id_counter = 1

@app.post("/api/blur")
async def upload_and_blur(
    file: UploadFile = File(...),
    options: str = Form(...),
    person_images: list[UploadFile] = File([]),
    emoji_images: list[UploadFile] = File([]),
    background_tasks: BackgroundTasks = None
):
    global video_id_counter
    current_id = video_id_counter
    video_id_counter += 1

    local_input_path = os.path.join(LOCAL_INPUT_DIR, f"input_{current_id}.mp4")
    local_output_path = os.path.join(LOCAL_OUTPUT_DIR, f"output_{current_id}.mp4")
    drive_final_path = os.path.join(DRIVE_OUTPUT_DIR, f"output_{current_id}.mp4")

    with open(local_input_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    parsed_options = json.loads(options)
    person_img_dict = {f.filename: await f.read() for f in person_images}

    dynamic_registered_people = []
    for opt in parsed_options:
        person_id = opt.get("person_id")
        action = opt.get("action", "blur")
        img_filename = opt.get("image_filename")
        emoji_filename = opt.get("emoji_filename", "cat.png")

        if img_filename not in person_img_dict: continue

        encodings = augment_and_encode_image(person_img_dict[img_filename])
        if not encodings: continue

        emoji_cv_img = None
        if action == "emoji" and emoji_filename:
            drive_emoji_path = os.path.join(DRIVE_EMOJI_DIR, emoji_filename)
            if os.path.exists(drive_emoji_path):
                emoji_cv_img = cv2.imread(drive_emoji_path, cv2.IMREAD_UNCHANGED)
            else:
                backup_path = os.path.join("/content/drive/MyDrive", emoji_filename)
                if os.path.exists(backup_path):
                    emoji_cv_img = cv2.imread(backup_path, cv2.IMREAD_UNCHANGED)

        dynamic_registered_people.append({
            "person_id": person_id,
            "action": action,
            "encodings": encodings,
            "emoji_img": emoji_cv_img
        })

    write_status_file(current_id, "PROCESSING")
    background_tasks.add_task(blur_video_processing_task, current_id, local_input_path, local_output_path, drive_final_path, dynamic_registered_people)
    return {"video_id": current_id, "status": "PROCESSING"}

@app.get("/api/blur/status/{video_id}")
def check_status(video_id: int): return read_status_file(video_id)

# 리액트 크롬 보안 필터 해제
@app.get("/api/blur/download/{video_id}")
def download_video(video_id: int):
    local_output_path = os.path.join(LOCAL_OUTPUT_DIR, f"output_{video_id}.mp4")

    if not os.path.exists(local_output_path):
        return {"error": "File not found"}, 404

    # 강제 CORS 해방 헤더 마킹
    headers = {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
        "Access-Control-Allow-Headers": "*"
    }

    return FileResponse(local_output_path, media_type="video/mp4", headers=headers)

import uvicorn
from pyngrok import ngrok

# 1. ngrok 인증 토큰 설정
NGROK_TOKEN = "36c0wZjhTifgdHyI5UurMS6r0R4_81LgVCL8oWAE64YVpimWm"
ngrok.set_auth_token(NGROK_TOKEN)

# 2. 8000번 포트로 외부 공개 터널 열기
public_url = ngrok.connect(8000)
print("\n" + "="*50)
print("프론트엔드 API Base URL에 아래 주소 작성")
print(public_url)
print("="*50 + "\n")

# 3. FastAPI 서버 가동
config = uvicorn.Config(app, host="0.0.0.0", port=8000, loop="asyncio")
server = uvicorn.Server(config)
await server.serve()